import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import Image from "next/image"
import deved from "../../public/dev-ed-wave.png"
import design from "../../public/design.png"
import code from "../../public/code.png"
import consulting from "../../public/consulting.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Vishu{"'"}s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Vishu Bansal</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className=" cursor-pointer text-2xl"/></li>
              <li><a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Vishu Bansal</h2>
            <h3 className=" text-2xl py-2">Full Stack Web Developer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              A Engineering Student who is interested in programming and various other fields. Just exploring different things.
              I am also a freelancer that can fulfill your development needs quickly and elegantly.
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillGithub/>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" alt="" />
          </div>
        </section>

        {/* section second */}

        <section>
          <div>
            <h3 className=" text-3xl py-1">Services I offer</h3>
            <p className=" text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelancer lorem ipsum somthing for sure 
              definately {"I'"}ve done remote work for... props somthing
              Since the <span className=" text-teal-600">beginning of my journey</span> as a freelancer lorem ipsum somthing for sure 
              definately {"I'"}ve done remote work for... props somthing
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800">
              I offer from a wide range fo services, including making projects for your work,
              making fully functioning full stack site or even small landing pages. whatever is your need 
              I can complete it for you for sweet cash.
            </p>
          </div>
          <div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} style={{margin: "auto",}} alt=""/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiul Dsigns</h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following coding design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Design tolls I used
              </h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} style={{margin: "auto",}} alt=""/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiul Dsigns</h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following coding design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Design tolls I used
              </h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} style={{margin: "auto",}} alt=""/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiul Dsigns</h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following coding design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Design tolls I used
              </h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
