import Head from "next/head";
import {BsFillMoonStarsFill, BsFillSunriseFill} from "react-icons/bs"
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import Image from "next/image"
import deved from "../../public/dev-ed-wave.png"
import design from "../../public/design.png"
import code from "../../public/code.png"
import consulting from "../../public/consulting.png"
import web1 from "../../public/web1.png"
import web2 from "../../public/web2.png"
import web3 from "../../public/web3.png"
import web4 from "../../public/web4.png"
import web5 from "../../public/web5.png"
import web6 from "../../public/web6.png"
import { useState } from "react";
import Link from "next/link";

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Vishu{"'"}s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">vbstellar</h1>
            <ul className="flex items-center">
              <li className="hover:text-gray-400"><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl"/></li>
              {/* <li><BsFillSunriseFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl"/></li> */}
              <li><a href="https://resume.io/r/Y6q4mHQB6" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8 hover:bg-gradient-to-l">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">Vishu Bansal</h2>
            <h3 className=" text-2xl py-2 md:text-3xl dark:text-white">Full Stack Web Developer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
              A Engineering Student who is interested in programming. I love to build web apps and can make full stack web applications.
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.twitter.com/vbstellar" className="hover:text-blue-400" ><AiFillTwitterCircle/></a>
            <a href="https://www.linkedin.com/in/vishuban/" className="hover:text-blue-800" ><AiFillLinkedin/></a>
            <a href="https://www.github.com/vbstellar" className="hover:text-black" ><AiFillGithub/></a>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="" />
          </div>
        </section>

        {/* section second */}

        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelancer lorem ipsum somthing for sure 
              definately {"I'"}ve done remote work for... props somthing
              Since the <span className=" text-teal-600">beginning of my journey</span> as a freelancer lorem ipsum somthing for sure 
              definately {"I'"}ve done remote work for... props somthing
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range fo services, including making projects for your work,
              making fully functioning full stack site or even small landing pages. whatever is your need 
              I can complete it for you for sweet cash.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-300 ">
              <Image src={design} width={100} height={100} className="mx-auto" alt=""/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiul Dsigns</h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following coding design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Design tolls I used
              </h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-300">
              <Image src={code} width={100} height={100} className="mx-auto" alt=""/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiul Dsigns</h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following coding design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Design tolls I used
              </h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-300">
              <Image src={consulting} width={100} height={100} className="mx-auto" alt=""/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiul Dsigns</h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following coding design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Design tolls I used
              </h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
          </div>
        </section>

        {/* section 3 */}
        <section className="pb-20">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            A web developer living in Delhi who <span className="text-teal-600"> works remotely and freelances</span> is a professional who creates and maintains websites for clients while working from the comfort of their own home. This individual has the technical skills and experience required to design and develop websites that meet the specific needs of their clients, including aspects such as user interface, functionality, and compatibility with different devices and web browsers.  
            </p>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" alt=""></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" alt=""></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" alt=""></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" alt=""></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" alt=""></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" alt=""></Image>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
